name: 'Testing trigger target'
on:
  repository_dispatch:
    types: [trigger-workflow01]

jobs:
  variableCollections:
    runs-on: ubuntu-latest
    outputs:
      target_repository: ${{ steps.variableExtraction.outputs.TARGET_REPOSITORY }}
      target_branch: ${{ steps.variableExtraction.outputs.TARGET_BRANCH }}
      target_argument: ${{ steps.variableExtraction.outputs.TARGET_ARGUMENT }}

    steps:
      - name: 'Variable Extraction'
        id: 'variableExtraction'
        run: |
          echo "TARGET_BRANCH=${{ github.event.client_payload.target_branch }}" >> "$GITHUB_OUTPUT"
          echo "TARGET_REPOSITORY=${{ github.event.client_payload.target_repository }}" >> "$GITHUB_OUTPUT"
          echo "TARGET_ARGUMENT=${{ github.event.client_payload.target_argument }}" >> "$GITHUB_OUTPUT"
  

  target:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Code'
        uses: 'actions/checkout@v4'
        with:
          repository: ${{ jobs.variableCollections.outputs.target_repository }}
          ref: ${{ jobs.variableCollections.outputs.target_branch }}

      - name: 'Bash - Echo'
        shell: bash
        run: |
          echo "Hello ${{ jobs.variableCollestions.outputs.target_argument }}. This is Bash!"
          cat simple-test.txt
